name: flutter_book
description: flutter_book
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_calendar_carousel: ^2.4.0
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true